version: '3.9'

services:
  python-app:
    build:
      context: .
      dockerfile: python-app/Dockerfile
    ports:
      - "8000:8000"
      - "8765:8765"
      - "4840:4840"
      - "1883:1883"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  # Mount Docker socket
    environment:
      - PYTHONUNBUFFERED=1
      - PROJECT_NAME=${COMPOSE_PROJECT_NAME} # Use the Docker Compose project name dynamically
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - app-network

  react-app:
    build:
      context: ./react-app
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - app-network


  # nginx:
  #   image: nginx:latest
  #   volumes:
  #      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  #   ports:
  #     - "80:80"
  #   networks:
  #     - app-network

networks:
  app-network:
    driver: bridge
